-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 234,
  ["line_length"] = 7,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -19 / 64},
  ["sprite_count"] = 32,
  ["width"] = 190,
}
