-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 409,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {23 / 64, 16.5 / 64},
  ["sprite_count"] = 1,
  ["width"] = 422,
}
