-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 216,
  ["line_length"] = 2,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {22.5 / 64, 15 / 64},
  ["sprite_count"] = 16,
  ["width"] = 999,
}
