-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 1012,
  ["line_length"] = 8,
  ["lines_per_file"] = 2,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -28 / 64},
  ["sprite_count"] = 16,
  ["width"] = 188,
}
