-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 831,
  ["line_length"] = 6,
  ["lines_per_file"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {22 / 64, 32.5 / 64},
  ["sprite_count"] = 24,
  ["width"] = 426,
}
