-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 771,
  ["line_length"] = 6,
  ["lines_per_file"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {33.5 / 64, 2.5 / 64},
  ["sprite_count"] = 24,
  ["width"] = 449,
}
