-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 426,
  ["line_length"] = 10,
  ["lines_per_file"] = 3,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -81 / 64},
  ["sprite_count"] = 24,
  ["width"] = 88,
}
