-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 870,
  ["line_length"] = 7,
  ["lines_per_file"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -51 / 64},
  ["sprite_count"] = 24,
  ["width"] = 384,
}
