-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 247,
  ["line_length"] = 7,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {6 / 64, -27.5 / 64},
  ["sprite_count"] = 32,
  ["width"] = 202,
}
