-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 120,
  ["line_length"] = 3,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {-17.5 / 64, -51 / 64},
  ["sprite_count"] = 24,
  ["width"] = 421,
}
