-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 227,
  ["line_length"] = 6,
  ["lines_per_file"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {21.5 / 64, 19.5 / 64},
  ["sprite_count"] = 32,
  ["width"] = 231,
}
