-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 244,
  ["line_length"] = 5,
  ["lines_per_file"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {19.5 / 64, 30 / 64},
  ["sprite_count"] = 32,
  ["width"] = 347,
}
